# Generated by Django 3.2.15 on 2024-03-24 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долгота')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
