# Generated by Django 3.2.15 on 2024-03-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20240322_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_orders', to='foodcartapp.restaurant', verbose_name='Где приготовлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('processed', 'Processed'), ('delivered', 'Delivered')], default='created', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='card', max_length=10, verbose_name='Тип оплаты'),
        ),
    ]
