# Generated by Django 3.2.15 on 2024-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20240322_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1_created', 'Создан'), ('2_processed', 'Обработан'), ('3_cooking', 'Готовится'), ('4_delivered', 'Доставлен')], default='1_created', max_length=20, verbose_name='Статус'),
        ),
    ]
