# Generated by Django 3.2.15 on 2024-03-21 07:25
from django.core.validators import MinValueValidator
from django.db import migrations
from django.db.models import F, DecimalField


def calculate_orderitem_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.annotate(product_price=F('product__price')).all()
    for order_item in order_items.iterator():
        order_item.price = order_item.product_price
        order_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=DecimalField(max_digits=7, decimal_places=2, verbose_name='Стоимость',
                               validators=[MinValueValidator(0)], null=True)
        ),
        migrations.RunPython(calculate_orderitem_price)
    ]
