# Generated by Django 3.2.15 on 2024-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20240322_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Картой онлайн')], default='card', max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('processed', 'Обработан'), ('delivered', 'Доставлен')], default='created', max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
