# Generated by Django 3.2.15 on 2024-03-30 15:58

from django.db import migrations


def fill_price_from_product(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.filter(price__isnull=True):
        if item.product:
            item.price = item.product.price
            item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0051_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RunPython(fill_price_from_product)
    ]
